### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by filip326** [Barsch2006/TypeScript-Window-UserList#2]
The command net user {username} /domain is running twice per user. the program could perform better by optimizing it.

**Comment by chfuchte** [comment]
Sure? It shouldn't

**Comment by chfuchte** [comment]
So on my Users.json there is only one line per User (4)

**Comment by chfuchte** [comment]
It should be fixed now by an automatic deletion of  your .json file when the program starts running. Maybe, you have forgotten to delete the file and ran the command multiple times

**Comment by filip326** [comment]
First command execution: https://github.com/Barsch2006/TypeScript-Window-UserList/blob/eedebd22b72617c4bf88a5cbb11bb33bca967147/src/User.ts#L32

Second command execution:
https://github.com/Barsch2006/TypeScript-Window-UserList/blob/eedebd22b72617c4bf88a5cbb11bb33bca967147/src/User.ts#L46

**Comment by chfuchte** [comment]
Sorry about that ;) 
fixed
